### ISSUE TITLE
Incompatible with Searchkick 4.0.2

### ISSUE THREAD

**Issue by archonic** [ddnexus/pagy#166]
Somewhere between searchkick 4.0.0 and 4.0.2 an incompatibility was introduced.

Calling
```
@pagy_s, @resources = pagy_searchkick( search_results )
```
now raises `undefined method 'search' for #<Class:0x000055cb53780f18> Did you mean? searchkick`.

I haven't looked into the details yet but I figured I'd create the issue sooner rather than later.

**Comment by ddnexus** [comment]
Thank you! I will check it ASAP.

**Comment by ddnexus** [comment]
@archonic It works as expected also with 4.0.2.
The `search` method is added to the model by searchkick and the API didn't change.
Maybe you are searching a model that is not searchkick enabled?

**Comment by archonic** [comment]
I'll see if I can reproduce it minimally. It was on a searchkick enabled model and only downgrading the gem fixed the issue.

**Comment by archonic** [comment]
I must have had something funky with an initializer or a bad state in my docker image gemset. Everything is working with Searchkick 4.0.2. My bad!
